name       : gdk-pixbuf
version    : 2.36.7
release    : 26
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.7.tar.xz : 1b6e5eef09d98f05f383014ecd3503e25dfb03d7e5b5f5904e5a65b049a6a4d8
homepage   : http://www.gnome.org
license    : LGPL-2.1
component  : desktop.gtk
summary    : GNOME toolkit for image loading and pixel buffer manipulation
description: |
    The Gdk Pixbuf is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(libpng15)
    - pkgconfig32(libpng15)
    - pkgconfig(libpcre)
    - pkgconfig32(libpcre)
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - librsvg
    - librsvg-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr --disable-static --with-x11
build      : |
    %make
install    : |
    %make_install
    cp %libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/.
    LD_LIBRARY_PATH=$installdir/%libdir% $installdir/usr/bin/gdk-pixbuf-query-loaders $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@$installdir/@@g" > $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders.cache
    rm $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so
