name       : gdk-pixbuf
version    : 2.36.11
release    : 31
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.11.tar.xz : ae62ab87250413156ed72ef756347b10208c00e76b222d82d9ed361ed9dde2f3
homepage   : http://www.gnome.org
license    : LGPL-2.1
component  : desktop.gtk
summary    : GNOME toolkit for image loading and pixel buffer manipulation
description: |
    The Gdk Pixbuf is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(libpng15)
    - pkgconfig32(libpng15)
    - pkgconfig(libpcre)
    - pkgconfig32(libpcre)
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig32(mount)
    - docbook-xml
    - gtk-doc
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - librsvg
    - librsvg-32bit
rundeps    :
    - shared-mime-info
emul32     : yes
optimize   : speed
setup      : |
    %apply_patches
    export LC_ALL=en_US.utf8
    %meson_configure -Dwith_docs=true
build      : |
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
    cp %libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/.
    LD_LIBRARY_PATH=$installdir/%libdir% $installdir/usr/bin/gdk-pixbuf-query-loaders $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@$installdir/@@g" > $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders.cache
    rm $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so

    # Sigh - remember when these were optional?
    rm -rf $installdir/%libdir%/gdk-pixbuf/installed-tests
    rmdir $installdir/%libdir%/gdk-pixbuf
    rm -rf $installdir/usr/share/installed-tests
