name       : gdk-pixbuf
version    : 2.42.6
release    : 44
source     :
    - https://download.gnome.org/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.6.tar.xz : c4a6b75b7ed8f58ca48da830b9fa00ed96d668d3ab4b1f723dcf902f78bde77f
homepage   : https://developer.gnome.org/gdk-pixbuf/
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : GNOME toolkit for image loading and pixel buffer manipulation
description: |
    The Gdk Pixbuf is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libpcre)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(mount)
    - pkgconfig(shared-mime-info)
    - docbook-xml
    - gtk-doc
    - librsvg
    - librsvg-32bit
rundeps    :
    - shared-mime-info
emul32     : yes
optimize   : speed
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dgtk_doc=false -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
    cp %libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/.
    LD_LIBRARY_PATH=$installdir/%libdir% $installdir/usr/bin/gdk-pixbuf-query-loaders $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@$installdir/@@g" > $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders.cache
    rm $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so

    # Sigh - remember when these were optional?
    rm -rf $installdir/%libdir%/gdk-pixbuf/installed-tests
    rmdir $installdir/%libdir%/gdk-pixbuf
    rm -rf $installdir/usr/share/installed-tests
