name       : gdk-pixbuf
version    : 2.32.3
release    : 19
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.32/gdk-pixbuf-2.32.3.tar.xz : 2b6771f1ac72f687a8971e59810b8dc658e65e7d3086bd2e676e618fd541d031
homepage   : http://www.gnome.org
license    :
    - LGPL-2.1
summary    : GNOME toolkit for image loading and pixel buffer manipulation
component  : desktop.gtk
builddeps  :
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(libpng15)
    - pkgconfig32(libpng15)
    - pkgconfig(libpcre)
    - pkgconfig32(libpcre)
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - librsvg
    - librsvg-32bit
emul32     : yes
optimize   : speed
description: |
    The Gdk Pixbuf is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
setup      : |
    %configure --prefix=/usr --disable-static --with-x11
build      : |
    %make
install    : |
    %make_install
    cp %libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/.
    LD_LIBRARY_PATH=$installdir/%libdir% $installdir/usr/bin/gdk-pixbuf-query-loaders $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@$installdir/@@g" > $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders.cache
    rm $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so
