name       : gdk-pixbuf
version    : 2.36.12
release    : 32
source     :
    - https://download.gnome.org/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.12.tar.xz : fff85cf48223ab60e3c3c8318e2087131b590fd6f1737e42cb3759a3b427a334
homepage   : http://www.gnome.org
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : GNOME toolkit for image loading and pixel buffer manipulation
description: |
    The Gdk Pixbuf is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libpcre)
    - pkgconfig32(libpng15)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(mount)
    - pkgconfig32(x11)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpcre)
    - pkgconfig(libpng15)
    - pkgconfig(libtiff-4)
    - pkgconfig(shared-mime-info)
    - pkgconfig(x11)
    - docbook-xml
    - glibc-32bit-devel
    - gtk-doc
    - libgcc-32bit
    - libjpeg-turbo-32bit-devel
    - libjpeg-turbo-devel
    - librsvg
    - librsvg-32bit
rundeps    :
    - shared-mime-info
emul32     : yes
optimize   : speed
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure -Ddocs=true
build      : |
    export LC_ALL=en_US.utf8
    %ninja_build
install    : |
    export LC_ALL=en_US.utf8
    %ninja_install
    cp %libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/.
    LD_LIBRARY_PATH=$installdir/%libdir% $installdir/usr/bin/gdk-pixbuf-query-loaders $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*.so | sed "s@$installdir/@@g" > $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders.cache
    rm $installdir/%libdir%/gdk-pixbuf-2.0/2.10.0/loaders/lib*svg*.so

    # Sigh - remember when these were optional?
    rm -rf $installdir/%libdir%/gdk-pixbuf/installed-tests
    rmdir $installdir/%libdir%/gdk-pixbuf
    rm -rf $installdir/usr/share/installed-tests
